### ISSUE TITLE
Setup CI build on travis for Linux/MacOSX build

### ISSUE THREAD

**Issue by eByte23** [SapientGuardian/mysql-connector-net-netstandard#8]
@sapientguardian A build should probably be setup on travis so that we know if the package also builds on linux and Mac OSX, especially seeing as I will be using this on linux :smile:

**Comment by SapientGuardian** [comment]
I'm using it on Linux as well. Since this is pure C# I don't know why it wouldn't be able to compile on there (so far I've been compiling on Windows, but deploying in Linux Docker containers). That said, I'm not opposed to a Travis build as long as it doesn't conflict with AppVeyor. I can look into getting this set up.

**Comment by eByte23** [comment]
Yeah I can only assume it should just work.
Yeah it is easy enough for you to setup and doesn't conflict for you  wouldbe awesome.

Possibly have a look at some of the dotnet projects as I think they run  multiple builds.

**Comment by eByte23** [comment]
Looks like dotnet projects now use a private jenkins server. But reading a random  documentation guide it looks possible?
For reference. http://example-project.readthedocs.io/en/latest/DevelopmentServices.html

**Comment by IntelOrca** [comment]
I think you need to select the Ubuntu 14.04 environment (see https://docs.travis-ci.com/user/ci-environment/).

Then it should just be a case of following https://www.microsoft.com/net/core#ubuntu
